[package]
name = "bril2json"
authors = ["Ethan Uppal"]
version = "0.1.0"
edition = "2021"

[dependencies]
bril-frontend = "0.2.0"
annotate-snippets = "0.11.5"
snafu = "0.8.5"
argh = "0.1.13"
serde_json = "1.0.138"
